image: python:3

stages:
  - test

test-2.7:
  image: python:2.7
  stage: test
  script:
    - pip install tox
    - tox -e py27

test-3.4:
  image: python:3.4
  stage: test
  script:
    - pip install tox
    - tox -e py34

test-3.6:
  image: python:3.6
  stage: test
  script:
    - pip install tox
    - tox -e py36

test-3.7:
  image: python:3.7
  stage: test
  script:
    - pip install tox
    - tox -e py37
